# Using Random forest

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
df = pd.read_csv('/content/breast-cancer-wisconsin.csv',header=None)
df

0   1   2   3   4   5     6   7   8   9   10
0    1000025   5   1   1   1   2   1.0   3   1   1   2
1    1002945   5   4   4   5   7  10.0   3   2   1   2
2    1015425   3   1   1   1   2   2.0   3   1   1   2
3    1016277   6   8   8   1   3   4.0   3   7   1   2
4    1017023   4   1   1   3   2   1.0   3   1   1   2
..       ...  ..  ..  ..  ..  ..   ...  ..  ..  ..  ..
694   776715   3   1   1   1   3   2.0   1   1   1   2
695   841769   2   1   1   1   2   1.0   1   1   1   2
696   888820   5  10  10   3   7   3.0   8  10   2   4
697   897471   4   8   6   4   3   4.0  10   6   1   4
698   897471   4   8   8   5   4   5.0  10   4   1   4

[699 rows x 11 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 699 entries, 0 to 698
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       699 non-null    int64  
 1   1       699 non-null    int64  
 2   2       699 non-null    int64  
 3   3       699 non-null    int64  
 4   4       699 non-null    int64  
 5   5       699 non-null    int64  
 6   6       683 non-null    float64
 7   7       699 non-null    int64  
 8   8       699 non-null    int64  
 9   9       699 non-null    int64  
 10  10      699 non-null    int64  
dtypes: float64(1), int64(10)
memory usage: 60.2 KB


In [4]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer.fit(x[:, 6:7])

x[:, 6:7] = imputer.transform(x[:, 6:7]) # add mean to missing values in col 6

In [6]:
x[:6]

array([[1.000025e+06, 5.000000e+00, 1.000000e+00, 1.000000e+00,
        1.000000e+00, 2.000000e+00, 1.000000e+00, 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.002945e+06, 5.000000e+00, 4.000000e+00, 4.000000e+00,
        5.000000e+00, 7.000000e+00, 1.000000e+01, 3.000000e+00,
        2.000000e+00, 1.000000e+00],
       [1.015425e+06, 3.000000e+00, 1.000000e+00, 1.000000e+00,
        1.000000e+00, 2.000000e+00, 2.000000e+00, 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.016277e+06, 6.000000e+00, 8.000000e+00, 8.000000e+00,
        1.000000e+00, 3.000000e+00, 4.000000e+00, 3.000000e+00,
        7.000000e+00, 1.000000e+00],
       [1.017023e+06, 4.000000e+00, 1.000000e+00, 1.000000e+00,
        3.000000e+00, 2.000000e+00, 1.000000e+00, 3.000000e+00,
        1.000000e+00, 1.000000e+00],
       [1.017122e+06, 8.000000e+00, 1.000000e+01, 1.000000e+01,
        8.000000e+00, 7.000000e+00, 1.000000e+01, 9.000000e+00,
        7.000000e+00, 1.000000e+00]])

In [7]:
y[:6]

array([2, 2, 2, 2, 2, 4])

In [8]:
y = y.reshape(len(y),1)  # make it 2D array

In [9]:
# lable encoder

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)
y[:6] # converted 2 and 4 to 0 and 1

/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 1])

In [10]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 0)

In [11]:
from sklearn.preprocessing import StandardScaler

# apply feature scaling to only numerical values not encoded values as it will chamge encoded values
# we dont want to change encoded values to be transfomed
# in short we dont apply feature scaling on dummy data
sc = StandardScaler()
x_train[:, 0:1] = sc.fit_transform(x_train[:, 0:1])

# here if we use fit_tansform then it will create new scaler and we dont want to that we want test to be in same format as train ony
x_test[:,  0:1] = sc.transform(x_test[:, 0:1])

In [12]:
x_train

array([[-1.08564892, 10.        ,  4.        , ...,  2.        ,
         3.        ,  1.        ],
       [ 0.13804167,  9.        , 10.        , ...,  3.        ,
         3.        ,  1.        ],
       [-0.13312821,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       ...,
       [ 0.38253213,  4.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [ 0.62721986,  5.        ,  1.        , ...,  2.        ,
         1.        ,  1.        ],
       [-1.4049915 ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ]])

In [13]:
x_test

array([[ 0.56564684,  4.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ],
       [-0.45312202,  4.        ,  2.        , ...,  2.        ,
         1.        ,  1.        ],
       [ 0.09213167,  6.        ,  6.        , ...,  7.        ,
         8.        ,  1.        ],
       ...,
       [-0.91725839,  7.        ,  5.        , ...,  5.        ,
         3.        ,  1.        ],
       [ 0.36497243,  3.        ,  1.        , ...,  2.        ,
         1.        ,  1.        ],
       [ 0.10858379,  1.        ,  1.        , ...,  2.        ,
         1.        ,  2.        ]])

In [16]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=100) 
regressor.fit(x_train, y_train)            

RandomForestClassifier()

In [17]:
prediction = regressor.predict(x_test)
prediction

array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0])

In [18]:
prediction = prediction.reshape(len(prediction),1)
prediction.size

140

In [19]:
y_test = y_test.reshape(len(y_test),1)
y_test.size

140

In [20]:
acc_train = regressor.score(x_train,y_train)
acc_train

1.0

In [21]:
acc = regressor.score(x_test,y_test)
acc

0.9785714285714285

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, prediction)

array([[83,  2],
       [ 1, 54]])

## Accuracy based on Prediction and test value

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, prediction)

0.9785714285714285